# Validation curve

A validation curve shows the validation and training score of an estimator for some varing hyper-parameter.

In [3]:
import numpy as np
from sklearn.model_selection import validation_curve
from sklearn.datasets import load_iris
from sklearn.linear_model import Ridge

np.random.seed(0)
iris = load_iris()
X, y = iris.data, iris.target
indices = np.arange(y.shape[0])
np.random.shuffle(indices)
X, y = X[indices], y[indices]

train_scores, valid_scores = validation_curve(Ridge(), X, y, "alpha", np.logspace(-7, 3, 3))
train_scores

array([[0.94141575, 0.92944161, 0.92267644],
       [0.94141563, 0.92944153, 0.92267633],
       [0.47253778, 0.45601093, 0.42887489]])

In [4]:
valid_scores

array([[0.90335825, 0.92525985, 0.94159336],
       [0.90338529, 0.92523396, 0.94159078],
       [0.44639995, 0.39639757, 0.4567671 ]])

If the training score and the validation score are both low, the estimator will be underfitting. If the training score is high and the validation score is low, the estimator is overfitting and otherwise it is working very well. A low training score and a high validation score is usually not possible.

# Learning curve

A learning curve shows the validation and training score of an estimator for varing numbers of training samples. It is a tools to find out how much we benefit from adding more training data and whether the estimator suffers more from a variance error or a bias error.

If both the validation score and the training score converge to a value that is too low with increasing size of the training set, we will not benefit much from more training data.

In [7]:
from sklearn.model_selection import learning_curve
from sklearn.svm import SVC

train_sizes, train_scores, valid_scores = learning_curve(SVC(kernel='linear'), X, y, train_sizes=[50, 80, 110], cv=5)
train_sizes

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:1103: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if np.issubdtype(train_sizes_abs.dtype, np.float):


array([ 50,  80, 110])

In [8]:
train_scores

array([[0.98      , 0.98      , 0.98      , 0.98      , 0.98      ],
       [0.9875    , 1.        , 0.9875    , 0.9875    , 0.9875    ],
       [0.98181818, 1.        , 0.98181818, 0.98181818, 0.99090909]])

In [9]:
valid_scores

array([[1.        , 0.93333333, 1.        , 1.        , 0.96666667],
       [1.        , 0.96666667, 1.        , 1.        , 0.96666667],
       [1.        , 0.96666667, 1.        , 1.        , 0.96666667]])